name: juneflow
description: "JuneFlow Project"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/juneflow

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  june_flow_util: ^0.8.20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true